# Generated by Django 5.0.4 on 2024-04-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaDjango', '0002_alter_empleado_habilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='habilidad',
            new_name='habilidades',
        ),
    ]
