# Generated by Django 5.0.4 on 2024-05-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaDjango', '0003_rename_habilidad_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(default='imagen.jpg', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='appEmpresaDjango.habilidad'),
        ),
    ]
