

services:
  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
    depends_on:
      - db
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    ports:
      - "8080:8080"
    command: npm run serve

volumes:
  mariadb_data:
